from django.db import models

# Create your models here.
class IMG(models.Model):
    img = models.ImageField(upload_to='img')
    number = models.CharField(max_length=1)
    eigenvalue = models.CharField(max_length=3,default=0)
    col0 = models.CharField(max_length=30)
    col1 = models.CharField(max_length=30)
    col2 = models.CharField(max_length=30)
    col3 = models.CharField(max_length=30)
    col4 = models.CharField(max_length=30)
    col5 = models.CharField(max_length=30)
    col6 = models.CharField(max_length=30)
    col7 = models.CharField(max_length=30)
    col8 = models.CharField(max_length=30)
    col9 = models.CharField(max_length=30)
    col10 = models.CharField(max_length=30)
    col11 = models.CharField(max_length=30)
    col12 = models.CharField(max_length=30)
    col13 = models.CharField(max_length=30)
    col14 = models.CharField(max_length=30)
    col15 = models.CharField(max_length=30)
    col16 = models.CharField(max_length=30)
    col17 = models.CharField(max_length=30)
    col18 = models.CharField(max_length=30)
    col19 = models.CharField(max_length=30)
    col20 = models.CharField(max_length=30)
    col21 = models.CharField(max_length=30)
    col22 = models.CharField(max_length=30)
    col23 = models.CharField(max_length=30)
    col24 = models.CharField(max_length=30)
    col25 = models.CharField(max_length=30)
    col26 = models.CharField(max_length=30)
    col27 = models.CharField(max_length=30)