# Generated by Django 2.0.3 on 2018-03-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('number', models.CharField(max_length=1)),
                ('col0', models.CharField(max_length=30)),
                ('col1', models.CharField(max_length=30)),
                ('col2', models.CharField(max_length=30)),
                ('col3', models.CharField(max_length=30)),
                ('col4', models.CharField(max_length=30)),
                ('col5', models.CharField(max_length=30)),
                ('col6', models.CharField(max_length=30)),
                ('col7', models.CharField(max_length=30)),
                ('col8', models.CharField(max_length=30)),
                ('col9', models.CharField(max_length=30)),
                ('col10', models.CharField(max_length=30)),
                ('col11', models.CharField(max_length=30)),
                ('col12', models.CharField(max_length=30)),
                ('col13', models.CharField(max_length=30)),
                ('col14', models.CharField(max_length=30)),
                ('col15', models.CharField(max_length=30)),
                ('col16', models.CharField(max_length=30)),
                ('col17', models.CharField(max_length=30)),
                ('col18', models.CharField(max_length=30)),
                ('col19', models.CharField(max_length=30)),
                ('col20', models.CharField(max_length=30)),
                ('col21', models.CharField(max_length=30)),
                ('col22', models.CharField(max_length=30)),
                ('col23', models.CharField(max_length=30)),
                ('col24', models.CharField(max_length=30)),
                ('col25', models.CharField(max_length=30)),
                ('col26', models.CharField(max_length=30)),
                ('col27', models.CharField(max_length=30)),
            ],
        ),
    ]
