# Generated by Django 2.0.3 on 2018-03-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='eigenvalue',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
